### ISSUE TITLE
[Bug] Está transformando letras maiúsculas ao invés de somente minúsculas

### ISSUE THREAD

**Issue by tassolacerda** [Nikaelson/Alura-challenge-one#1]
Olá Nikaelson, tudo bom? Salve, sou do Nordeste também, me chamo Paulo de Tasso e sou um colega da Alura Oracle One. Vim aqui dar os parabéns pelo seu projeto, ficou muito bom, e vim fazer uma observação sobre um bug.

Na sua aplicação fala sobre transformar apenas letras minúsculas e sem acento, só que ao digitar algum desses casos na textarea, pude perceber que ele faz essa criptografia, então vim falar sobre o motivo disso acontecer.

https://github.com/Nikaelson/Alura-challenge-one/blob/ab3bbef87b26205d02ba1e547053b29338c69d0e/criptografar.js#L25-L32

O /i serve para captar todas as letras sendo elas maiúsculas ou minúsculas, então no caso dessa aplicação, você pode deixar só o /g, pois assim ele vai caçar e mudar somente as letras sem acento. 

```

text = texto.toLowerCase()
text = text.replace(new RegExp('[ÁÀÂÃ]', 'g'), 'a')
text = text.replace(new RegExp('[ÉÈÊ]', 'g'), 'e')
text = text.replace(new RegExp('[ÍÌÎ]', 'g'), 'i')
text = text.replace(new RegExp('[ÓÒÔÕ]', 'g'), 'o')
text = text.replace(new RegExp('[ÚÙÛ]', 'g'), 'u')
text = text.replace(new RegExp('[Ç]', 'g'), 'c')`
  
```

  Isso faria com que ele ainda pegasse as letras maiúsculas por conta do `toLowerCase()`. Então, o que você pode fazer é deixar somente o outro replace que está no seu código. A função ficaria assim

```
let text = texto
    .replace(/e/g, 'enter')
    .replace(/i/g, 'imes')
    .replace(/a/g, 'ai')
    .replace(/o/g, 'ober')
    .replace(/u/g, 'ufat')

  return text
```
  
  
  Se você queria criptografar as letras maíusculas e com acento, minha informação fica mais de conhecimento mesmo, abraços irmão!

**Comment by Nikaelson** [comment]
Fala Pedro! tudo bem sim e com você?
Essa parte do código é justamente para tratar a entrada, pois não da pra confiar que o usuário vai seguir todas as recomendações né kkkk. Mas sua observação foi muito boa de qualquer forma. 
Abraços e vamos esperar o próximo desafio!

**Comment by tassolacerda** [comment]
Olá, obrigado pela resposta! Na questão do usuário, ele pode digitar as letras maiúsculas e com acento, no caso elas não vão poder ser convertidas. Sobre o próximo desafio, aguardo ansiosamente, a Alura está sendo incrível
